sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -t viktorzetterstrom/client-test -f ./client/Dockerfile.dev ./client
  - docker build -t viktorzetterstrom/api-test -f ./api/Dockerfile.dev ./api

script:
  - docker run -e CI=true viktorzetterstrom/client-test npm test
  - docker run viktorzetterstrom/api-test npm test

after_success:
  - docker build -t viktorzetterstrom/shl-client ./client
  - docker build -t viktorzetterstrom/shl-api ./api
  - docker build -t viktorzetterstrom/shl-proxy ./proxy
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push viktorzetterstrom/shl-client
  - docker push viktorzetterstrom/shl-api
  - docker push viktorzetterstrom/shl-proxy

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: shl
  env: Shl-env
  bucket_name: elasticbeanstalk-eu-north-1-302963688785
  bucket_path: shl
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
