version: '3'
services:
  redis:
    image: "redis:latest"

  api:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - "SHL_ID=${SHL_ID}"
      - "SHL_SECRET=${SHL_SECRET}"

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  proxy:
    restart: always
    depends_on:
      - client
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./proxy
    ports:
      - "3000:80"
